CREATE TABLE `user` (
   `id` varchar(50) NOT NULL COMMENT 'id',
   `phone` varchar(20) NOT NULL COMMENT '手机号',
   `login_name` varchar(50) NOT NULL COMMENT '登录名称',
   `name` varchar(30) NOT NULL COMMENT '用户名称',
   `password` varchar(50) NOT NULL COMMENT '密码',
   `contcat_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
   `id_type` tinyint(4) DEFAULT NULL COMMENT '证件类型',
   `id_number` varchar(32) DEFAULT NULL COMMENT '证件号码',
   `id_number_photo_back_url` varchar(200) DEFAULT NULL COMMENT '证件照片反面url',
   `id_number_photo_url` varchar(200) DEFAULT NULL COMMENT '证件照片正面url',
   `nickname` varchar(30) DEFAULT NULL COMMENT '昵称',
   `birthplace` varchar(150) DEFAULT NULL COMMENT '出生地',
   `home` varchar(100) DEFAULT NULL COMMENT '家庭住址',
   `company` varchar(100) DEFAULT NULL COMMENT '公司',
   `email` varchar(50) DEFAULT NULL COMMENT '电子邮箱',
   `last_login_time` varchar(20) DEFAULT NULL COMMENT '上次登录时间',
   `device_storehouse_id` int(11) DEFAULT NULL COMMENT '仓库id',
   `install_site_id` int(11) DEFAULT NULL COMMENT '安装点id',
   `iot_type_id` int(11) DEFAULT NULL COMMENT '运营商id',
   `operator_id` int(11) DEFAULT NULL COMMENT '运营公司id',
   `resident_id` int(11) DEFAULT NULL COMMENT '归属地id',
   `create_time` varchar(20) DEFAULT NULL COMMENT '创建时间',
   `update_time` varchar(20) DEFAULT NULL COMMENT '修改时间',
   `status` tinyint(4) DEFAULT '0' COMMENT '用户状态默认 0:启用',
   `system_id` varchar(20) NOT NULL COMMENT '系统id  0 公车 4生产检测平台 5地磁 6电动车 7消防栓 8七彩卡 9第三方',
   `tenant_id` varchar(20) DEFAULT '0' COMMENT '租户id',
   `extend1` varchar(25) DEFAULT NULL COMMENT '备用字段',
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表'